import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { getServerAuthUser } from "@/modules/auth/server-auth";
import { AuthProvider } from "@/modules/auth/auth-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serverUser = await getServerAuthUser();

  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={serverUser}>
          <Toaster richColors /> 
          {children}
          <footer className="border-t border-border/50 bg-muted/30">
            <div className="mx-auto max-w-7xl px-6 py-8 lg:px-8">
              <p className="text-center text-sm text-muted-foreground">
                © 2025 RetailZoom Web Development Team. Built with Next.js & ❤️
              </p>
            </div>
          </footer>
        </AuthProvider>
       
      </body>
    </html>
  );
}
